variables:
  DENO_VERSION: "v0.26.0"
  TS_VERSION: "3.7.0"

jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - bash: curl -L https://deno.land/x/install/install.sh | sh -s $(DENO_VERSION)
  - bash: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: $(HOME)/.deno/bin/deno run --allow-all test.ts

- job: 'Mac'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - bash: curl -L https://deno.land/x/install/install.sh | sh -s $(DENO_VERSION)
  - bash: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: $(HOME)/.deno/bin/deno run --allow-all test.ts

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: iwr https://deno.land/x/install/install.ps1 -out install.ps1; .\install.ps1 $(DENO_VERSION)
  - bash: echo "##vso[task.prependpath]C:\Users\VssAdministrator\.deno\\bin"
  - bash: deno.exe run --allow-all test.ts