name: CI

on: [push]

jobs:
  build:
    services:
      mysql:
        image: mysql:5.6
        ports:
          - 3307:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: denolib/deno-action@0.17.0
      with:
        args: run -A test.ts
      env:
        DB_PORT: 3307
